version: '2'
services:
  phpadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
      - PMA_USER=bn_opencart
        # - MYSQL_ROOT_PASSWORD=${DBPASS}
        # - MYSQL_PASSWORD=${DBPASS}
      - PMA_PASSWORD=${DBPASS}
    ports:
      - '${PHPADMIN_PORT}:80'

            
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
      - MARIADB_PASSWORD=${DBPASS}
      - MARIADB_ROOT_PASSWORD=${DBPASS}
    restart: always
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  opencart:
    image: docker.io/bitnami/opencart:4
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - OPENCART_HOST=${DOMEN}
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      - OPENCART_DATABASE_PASSWORD=${DBPASS}
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      # - ALLOW_EMPTY_PASSWORD=yes
    restart: always
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local
